ETLanza/wrk.out

- wrk.out.xcodeproj/project.pbxproj
- wrk.out/Constants.swift
- wrk.out/Models/Lift.swift
- wrk.out/Models/Set.swift
- wrk.out/Models/Workout.swift
Adds Workout model
Adds Set model
Adds Lift model
Adds Constants file for let constants
> Adds Model Obejcts

- wrk.out.xcodeproj/project.pbxproj
- wrk.out/Keys.swift
- wrk.out/Models/Lift.swift
- wrk.out/Models/Sets.swift
- wrk.out/Models/Workout.swift
Renames all structs to keys suffix
> Renames Constants files to keys

- wrk.out.xcodeproj/project.pbxproj
- wrk.out/Controllers/Model Controllers/WorkoutController.swift
- wrk.out/Models/Workout.swift
Adds WorkoutController CRUD functions and cloudkit fetch
> Adds WorkoutController and Functions

- wrk.out.xcodeproj/project.pbxproj
- wrk.out/Controllers/Model Controllers/PersonController.swift
- wrk.out/Controllers/TabBar Controller/CustomTabBar.swift
- wrk.out/Controllers/TabBar Controller/profileTabController.swift
- wrk.out/Controllers/View Controllers/profileVC.swift
- wrk.out/Controllers/View Controllers/profileViewController.swift
- wrk.out/Controllers/View Controllers/profiuleViewController.swift
- wrk.out/Controllers/View Controllers/routinesViewController.swift
- wrk.out/Models/Person.swift
- wrk.out/RoutineSectionHeader.swift
- wrk.out/Storyboards/Main.Storyboard
- wrk.out/Storyboards/TabBar.storyboard
- wrk.out/Storyboards/exercises.storyboard
- wrk.out/Storyboards/more.storyboard
- wrk.out/Storyboards/profile.storyboard
- wrk.out/Storyboards/routines.storyboard
- wrk.out/Storyboards/workouts.storyboard
- wrk.out/routinesHeaderCell.swift
> Fix merge conflict

- wrk.out.xcodeproj/project.pbxproj
- wrk.out/views/AddSetTableViewCell.swift
- wrk.out/views/FooterTableViewCell.swift
- wrk.out/views/HeaderTableViewCell.swift
- wrk.out/views/LiftHeaderTableViewCell.swift
- wrk.out/views/LiftsetTableViewCell.swift
Fix the invalidated linked for the pre-made table view cells
> Create custom table view cells for workout controller

- wrk.out/Controllers/Model Controllers/LiftController.swift
- wrk.out/Controllers/Model Controllers/LiftSetController.swift
- wrk.out/Controllers/View Controllers/WorkoutViewController.swift
- wrk.out/Models/Workout.swift
- wrk.out/Storyboards/Workouts.storyboard
- wrk.out/views/LiftHeaderTableViewCell.swift
Add swipe to delete lift cell
Add more button to delete lift section
Add completion handlers to liftset and lift delete functions
Add alertController to end workout and cancel workout buttons to prevent accidental button taps
> Add delete functionality to new workout tableview

- wrk.out/Controllers/Model Controllers/WorkoutController.swift
- wrk.out/Controllers/View Controllers/WorkoutViewController.swift
Add CloudKitModify to rename AC
Add completion handler to Workout delete function
> Edit rename alert controller

- wrk.out/Controllers/Model Controllers/LiftController.swift
- wrk.out/Controllers/View Controllers/LoadScreenViewController.swift
- wrk.out/Controllers/View Controllers/WorkoutViewController.swift
Correct the modify call on rename exercise function to rename the lift
> Add compleiton handler to modify lift function

- wrk.out/Controllers/View Controllers/LoadScreenViewController.swift
- wrk.out/Controllers/View Controllers/New Group/EditInfoPopupViewController.swift
- wrk.out/Resources/Assets.xcassets/wrkoutBlue.colorset/Contents.json
- wrk.out/Storyboards/Profile.storyboard
- wrk.out/Storyboards/TabBar.storyboard
Add logic to differentiate between new and old users
Onboard edit user popup controller to create new user
> Edit user onboarding

- wrk.out/Controllers/Model Controllers/WorkoutController.swift
- wrk.out/Controllers/View Controllers/WorkoutViewController.swift
- wrk.out/Models/Lift.swift
- wrk.out/Models/Workout.swift
- wrk.out/Storyboards/exercises.storyboard
Add and complete modify records for all alert controllers
Cloudkit now properly deletes and renames lifts, liftsets and workouts
> Finish modify records on cloudkit

- wrk.out/Models/User.swift
Change user model object to have working convenience initializer
Change CKRecord extension for init with User object
> Fix user onboarding and modify

- wrk.out.xcodeproj/project.pbxproj
- wrk.out/Controllers/Model Controllers/RoutineController.swift
- wrk.out/Controllers/View Controllers/RoutineViewController.swift
- wrk.out/Keys.swift
- wrk.out/Models/Routines.swift
- wrk.out/views/RoutineTableViewCell.swift
This adds blank files for RoutineViewController, the routine model object controller, the routineTableViewCell, and sets up the routine model object in its entirety with corresponding key constants
> blueprint for routines

- wrk.out/Controllers/View Controllers/WorkoutViewController.swift
- wrk.out/Storyboards/Workouts.storyboard
Adds if-else statements on workoutViewController to populate both tableViews correctly
> Add previous workout table view data source and delegate methods

- wrk.out.xcodeproj/project.pbxproj
- wrk.out/Controllers/Model Controllers/LiftController.swift
- wrk.out/Controllers/Model Controllers/WorkoutController.swift
- wrk.out/Controllers/View Controllers/LoadScreenViewController.swift
- wrk.out/Controllers/View Controllers/New Group/ExerciseViewControllerPopup.swift
- wrk.out/Controllers/View Controllers/WorkoutExerciseViewController.swift
- wrk.out/Controllers/View Controllers/WorkoutViewController.swift
- wrk.out/Storyboards/Exercises.storyboard
- wrk.out/Storyboards/TabBar.storyboard
- wrk.out/Storyboards/Workouts.storyboard
Add exercise presents Exercise API data to choose new exercises
> Change Add Exercise button

- wrk.out/Controllers/Model Controllers/WorkoutController.swift
- wrk.out/Models/Lift.swift
- wrk.out/Storyboards/Workouts.storyboard
- wrk.out/views/LiftsetTableViewCell.swift
Add the IBAction connection to the liftsetcell
Change the new workout routine to insert at 0, from .append
Less optimal preformance, for the desired UX
> Add ckreference for lift model to routine model

- wrk.out/Controllers/Model Controllers/RestTimerController.swift
- wrk.out/Controllers/View Controllers/MoreViewController.swift
- wrk.out/Controllers/View Controllers/WorkoutViewController.swift
- wrk.out/Storyboards/Workouts.storyboard
- wrk.out/Storyboards/more.storyboard
Add rest timer label into workout view controller
Add seconds label to more view controller
Add logic for "Done" button to activate and invalidate timer
Rest timer now displays alert controller when timer finishes
> Add rest-timer views and logic

- wrk.out/Storyboards/Workouts.storyboard
> Revert "Remove dynamic font warnings"

- wrk.out/AppDelegate.swift
- wrk.out/Controllers/View Controllers/MoreViewController.swift
- wrk.out/Controllers/View Controllers/WorkoutViewController.swift
- wrk.out/Storyboards/Profile.storyboard
Store rest timer isEnabled boolean and length with user defaults
> Implement userdefaults

- wrk.out.xcodeproj/project.pbxproj
- wrk.out/AppDelegate.swift
- wrk.out/Controllers/View Controllers/New Group/EditInfoPopupViewController.swift
- wrk.out/Resources/Info.plist
Text fields now resign first responder to see under keyboard
> Add textfield delegate to Edit Info Popup VC

- wrk.out/Controllers/View Controllers/New Group/EditInfoPopupViewController.swift
- wrk.out/Resources/Info.plist
- wrk.out/Storyboards/Profile.storyboard
Views now scale with different sized iphones
> Add constraints for all views

- wrk.out/Controllers/View Controllers/WorkoutViewController.swift
- wrk.out/Resources/Info.plist
- wrk.out/Storyboards/More.storyboard
- wrk.out/Storyboards/Workouts.storyboard
- wrk.out/Views/LiftsetTableViewCell.swift
Workout views no scale properly in different sized devices
> Fix Workout Views scaling

- wrk.out.xcodeproj/project.pbxproj
- wrk.out/Controllers/Model Controllers/LiftController.swift
- wrk.out/Controllers/Model Controllers/WorkoutController.swift
- wrk.out/Controllers/View Controllers/LoadScreenViewController.swift
- wrk.out/Controllers/View Controllers/PreviousWorkoutViewController.swift
- wrk.out/Controllers/View Controllers/ProfileViewController.swift
- wrk.out/Controllers/View Controllers/RoutineViewController.swift
- wrk.out/Controllers/View Controllers/WorkoutViewController.swift
- wrk.out/Storyboards/Profile.storyboard
- wrk.out/Storyboards/Workouts.storyboard
- wrk.out/TimeStringFormatter.swift
- wrk.out/Views/AddSetTableViewCell.swift
Add previous workouts to profile view
> Fix bugs with new workout from routine
